---
title: Pre-Workshop Prep
---

If you are participating in this workshop series, we are so excited to help you acquire new or hone existing technical and interpersonal skills in the realm of synthesis science! To ensure that you get the most out of this workshop series, **we recommend that you take the following steps _<u>before</u>_ the first week.**

::: {.callout-important}
#### Note on Organization-Owned Computers

If your organization has a dedicated IT team that has sole power to install software on your computer, you will need to contact them before the workshop to do the installation bits of the preparation steps we outline below.
:::

## Install R

"R" is the coding language we'll use throughout the workshop series. Follow the relevant instructions for your operating system here: [r-project.org](https://www.r-project.org/)

## Install Positron

***Positron*** is the <u>i</u>ntegrated <u>d</u>evelopment <u>e</u>nvironment (IDE) we'll use to write code to support the synthesis work you all will be accomplishing during (and after!) the workshop series. Follow the relevant instructions for your operating system here: [positron.posit.co](https://positron.posit.co/)

:::callout-note
### Positron vs. RStudio

You may already be familiar and comfortable with RStudio (we are too!).  Positron is the next generation IDE developed by the same folks who made RStudio, and it has better integration for Quarto, as well as Python and other coding languages.  Because this is the direction R for data science is heading, we figured it is worth making the leap for this workshop.

That said, nearly everything in this workshop will work equally well in RStudio!
:::

## Install Necessary R Packages

So-called "base R" contains some useful, fundamental operations from the moment you install it. However, there are a variety of external packages that contain more specific tools that can also be extremely useful to you. Most of these we will provide installation instructions for in the lessons that use them, but there are a few that it will benefit you to install now. In the "Console" pane of Positron, choose an option:

::: {.panel-tabset}

### {{< fa solid code >}} base R (standard)

This is the built-in function to install packages in R.  This is what you will most likely see "in the wild" and works well.
```r
install.packages("usethis")
install.packages("gitcreds")
```

::::{.callout-warning}
Do not use `install.packages()` in a script, though, since it will re-install the package every time you run it - not good practice for reproducibility or performance.
::::

### {{< fa solid code >}} `librarian` (recommended)

The `librarian` package is an improved way to install and manage R packages.  It will test to see if the package is already installed, and if not, it will install it for you, and then load the package.  This takes the place of `install.packages("<packagename>"); library(packagename)`.  
```r
install.packages("librarian")
librarian::shelf(usethis, gitcreds) # <1>
```
1. The `shelf` function will automatically install the packages that you don't already have and then load all the identified libraries

::::{.callout-tip}
Because `librarian::shelf()` checks to see if a package has already been installed, it is safe to include in a script!
::::
:::

## Install Quarto

***Quarto*** is the software we'll use to create computational notebook files. You may have previously worked with other types of notebook files (e.g., R Markdown files, Jupyter notebooks), but Quarto offers a number of advantages that make using it worthwhile. Follow the relevant instructions for your operating system here: [quarto.org/docs/get-started](https://quarto.org/docs/get-started/)

## Install Git

***Git*** is the name of the software that we can use to do "version control" for the code files we'll develop. We'll get into this more later but for now, it is enough to know this is analogous to Microsoft Word's "track changes" feature but with some extra features that are great for code files.

Installing Git differs slightly depending on your computer's operating system so check out the tabs below for the right option for you. These instructions are modified from Jennifer Bryan's excellent "[Happy Git and GitHub for the useR](https://happygitwithr.com/)" ebook.

:::{.panel-tabset}
### {{< fa brands apple >}} Mac

Run the following {{< fa terminal >}} command line code.

```
xcode-select --install
```

For more detailed instructions, see [here](https://happygitwithr.com/install-git#macos).

### {{< fa brands windows >}} Windows

[Install Git for Windows](https://gitforwindows.org/) (a.k.a. "Git Bash"). When asked about "Adjusting your PATH environment", **select "Git from the command line and also from 3rd-party software"**.

For more detailed instructions, see [here](https://happygitwithr.com/install-git#install-git-windows).

### {{< fa brands linux >}} Linux

Install Git via your distro's package manager (in the {{< fa terminal >}} Terminal).

If you use Ubuntu or Debian Linux that {{< fa terminal >}} code is as follows:

```
sudo apt-get install git
```

If instead you use Fedora or RedHat Linux the {{< fa terminal >}} code is instead:

```
sudo yum install git
```

For more detailed instructions, see [here](https://happygitwithr.com/install-git#linux).

:::

Check that the installation was successful by running the following {{< fa terminal >}} command line code in the terminal (you may need to restart your computer first): 

```bash
git --version
```

If successful, you should see something like `git version 2.40.1.windows.1`.


## Make a GitHub Account

***GitHub*** is a nice web interface for collaborating with other people who use Git. Later in the lifecycle of a project, GitHub is also useful for sharing and publicizing your code beyond of your team. 

**Please make a profile at [github.com](https://github.com/).** 

* If you have a .edu address, we recommend using that, as an educational account gives free access to certain privileges (you can always link an edu account later)
* Consider adding a profile photo. Doing so will make you stand out relative to the default 'space invader' image your account will start with.
