---
title: "Working Group Project Milestones"
format:
  theme-html:
    toc: false
---

::: column-margin
:::

## Overview

There are no universal benchmarks for how quickly a synthesis working group will proceed through the phases of a project's lifecycle. That said, the milestones below may prove helpful as a general 'how are we doing?' temperature check. If your group does not accomplish all of these--or proceeds beyond them--don't worry too much!

## Week 1 Benchmarks

:::{.panel-tabset}
### Before <u>Week 1</u>

Before arriving for the in-person component of the first week, <u>you</u> should have:

- Installed all necessary software
    - See the "Workshop Preparation" section of the [week 1 homepage](https://nceas-learning-hub.github.io/2026_delta_week1/)
- Made a profile on [github.com](https://github.com/)

### At the End of Week 1

After the first week, <u>your group</u> should have done (at least some of) the following:

- Defined the project's primary hypothesis
- Discussed and created formal documentation for:
    - Intellectual credit
    - Group interpersonal norms (e.g., code of conduct, distribution of administrative/logistical tasks)
- Identified (A) specific datasets relevant to the project and/or (B) data repositories likely to contain such data
- Drafted a project management plan with specific, actionable tasks for getting started on the project
- Begun collaborating (in GitHub) on code to harmonize, do quality control on, visualize, or perform preliminary analysis on relevant data
- Discussed the above actions with your project mentor(s)

### Before <u>Week 2</u>

Between the first and second weeks of the workshop, <u>your group</u> should have done (at least some of) the following:

- Written code (version-controlled and stored in GitHub) to:
    - Harmonize at least 5 datasets
    - Perform quality control on the harmonized dataset
    - Perform preliminary visualization of individual or synthesized datasets
- Documented scientific judgement calls made up to this point in a clear, human-readable manner
    - E.g., data in/exclusion criteria, data transformation(s), project question or scope changes
- Updated your project management system with specific, actionable tasks that _have not yet been done_ but need to be completed in the near future
- Identified areas of confusion (e.g., scientific, code-related) to discuss with workshop instructors and/or project mentors during week 2

:::
