---
title: "Reproducibility: a Lego Activity"
---

## Reproducibility activity using LEGO®

:::{.callout-learning}
After completing this session, you will be able to:

- Explain the importance of good documentation for reproducibility through the medium of LEGO®
- Identify challenges and good documentation practices to improve reproducibility
:::

::: callout-note
## Acknowledgments
This activity is largely based on the [LEGO® Metadata for Reproducibility game pack](http://eprints.gla.ac.uk/196477/), which was developed by [Mary Donaldson](https://orcid.org/0000-0002-1936-3499) and [Matt Mahon](https://orcid.org/0000-0001-8950-8422).
:::

## Getting started

1.  Gather into small groups
2.  Get LEGO® blocks and worksheets 
    * [instructions](resources/activity_reproducibility_lego/lego_activity_instructions.pdf)
    * [metadata template](resources/activity_reproducibility_lego/template_lego_activity_metadata.pdf)
3.  Follow <span style="background: yellow;">Creation phase instructions</span> (40-45 min)
4.  Hand off materials and metadata to another team (2 min)
5.  Follow <span style="background: #bbccff;">Replication phase instructions</span> (25-30 min)



<span style="color: #88888888;">(instructor guide [here](resources/activity_reproducibility_lego/instructional_guide_reproducibility_activity.pdf))</span>

At the end, we will discuss as a group.

## Discussion

<details>

<summary>Discussion Questions</summary>

-   Did you find this a simple way to document your process?
-   Was there anything you found difficult to capture?
-   Did those replicating the builds find it straightforward to follow?
-   Did you encounter any ambiguity in the instructions?

</details>

